config/routes.rb
Mappedin2::Application.routes.draw do
  match '/' => 'static_pages#index'
  match 'auth' => 'auth#index'
  match 'auth/callback', :to => 'auth#callback'
  get 'logout' => 'auth#destroy'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def index
  # get your api keys at https://www.linkedin.com/secure/developer
    client = LinkedIn::Client.new(ENV['CONSUMER_KEY'], ENV['CONSUMER_SECRET'])
    request_token = client.request_token(:oauth_callback => 
                                      "http://#{request.host_with_port}/auth/callback")
    session[:rtoken] = request_token.token
    session[:rsecret] = request_token.secret

    redirect_to client.request_token.authorize_url
  end

  def callback
     client = LinkedIn::Client.new(ENV['CONSUMER_KEY'], ENV['CONSUMER_SECRET'])
    if session[:atoken].nil?
       pin = params[:oauth_verifier]
       atoken, asecret = client.authorize_from_request(session[:rtoken], session[:rsecret], pin)
       session[:atoken] = atoken
       session[:asecret] = asecret
    else
       client.authorize_from_access(session[:atoken], session[:asecret])
    end
    @connections = client.connections
    @profile = client.profile
    @pcon = process_connections
  end
  
  def destroy
    session[:atoken] = nil
    redirect_to '/', :notice => "Signed out!"
    flash[:notice] = "You have been logged out." 
   end

  def process_connections
    counter = 0
    @rarr = Array.new(0,Hash.new)
    @connections.each do |con|
      loc_name = con.location.name.sub(/ Area/, '')
      loc_name = loc_name.sub(/ Bay/, '')
      loc_name = loc_name.sub(/Greater /, '')
      results = Geocoder.search loc_name
        if !results.empty?
	@rarr[counter] = 
		{:description => 
		"#{con.first_name} 
		 #{con.last_name} <BR>
		 #{loc_name}<BR> <a href=
		 #{con.site_standard_profile_request}>Profile</a><BR> <img src=
		 #{con.picture_url}>", :lat => results[0].latitude, :lng => results[0].longitude}
        counter+=1
        end
    end
  @process_connections = @rarr
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mappedin2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">MappedIN</a>
    <p class="navbar-text pull-right">
     <a class="navbar-link" href="#">	
	<%if !@profile.nil? %>
	Welcome
	<%="#{@profile.first_name}"%></a>
	<%= link_to "Sign Out", logout_url %>
	<% end %>
  </div>
    <div class="alert alert-info">
	<%if !@profile.nil? %>
        You currently have <%="#{@connections.length}"%> connections being mapped by MappedIN!  Click a Location to drill into your connections!
	<% end %>
    </div>
</div>
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
<style>
	footer[role="contentinfo"] {
            color: #666;
            background: #f5f5f5;
            padding: 18px 0;
        }
	html, body {
            height: 100%;
        }
        #push {
            height: 54px;
        }
        footer[role="contentinfo"] {
            height: 18px; /* accounts for padding */
        }
        body > .container {
            min-height: 100%;
            height: auto !important;
            height: 100%;
            margin: 0 auto -54px;
        }
</style>
</head>
<body>

<%= yield :scripts %>
<%= yield %>

<footer role="contentinfo">
      <div class="container">
        <p>Nick Drost, <A href="http://www.salesforce.com" target="_blank">salesforce.com</a>
	<a href="http://www.linkedin.com/in/nickdrost" style="text-decoration:none;"><span style="font: 80% Arial,sans-serif; color:#0783B6;"><img src="http://www.linkedin.com/img/webpromo/btn_in_20x15.png" width="20" height="15" alt="View Nick Drost's LinkedIn profile" style="vertical-align:middle" border="0">View Nick Drost's profile</span></a>
	</p>
      </div>
</footer>
</body>
</html>

app/views/static_pages/index.html.erb
<div class="container">
<body>
<div class="container"  style="text-align: center;">
<%= image_tag('shapeimage_2.png') %>
</div>
<BR>
<div class="container_foot" style="text-align: center;"><BR>
<h2>Who do you know where?</h2>
<%= link_to(image_tag("droppedImage.png"), :controller => "auth", :action => "index") %>
</div>

</body>
</div>